apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    lan-mode: private
    wan-mode: public

  name: argocd-route
spec:
  hostnames:
    - argo.writemy.codes
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main-gw
      namespace: kube-system

  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: argocd-server
          port: 443
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        backendRequest: 300s
        request: 300s
