apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gw

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  gatewayClassName: eg

  infrastructure:
    annotations:
      metallb.universe.tf/address-pool: pub-pool
      metallb.universe.tf/allow-shared-ip: main-gw
      purelb.io/allow-shared-ip: main-gw.resolvemy.host
      purelb.io/service-group: main-public
      purelb.io/allow-local: 'true'

  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: writemycodes-default-certificates
            namespace: core-prod

          - group: ''
            kind: Secret
            name: myloginspace-default-certificates
            namespace: core-prod

          - group: ''
            kind: Secret
            name: myloginspace-int-default-certificates
            namespace: core-prod
