apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

  annotations:
    argocd.argoproj.io/sync-wave: '0'

  labels:
    kubernetes.io/metadata.name: cert-manager

spec:
  finalizers:
    - kubernetes