apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home1-tls
  namespace: cert-manager
spec:
  generators:
    - list:
        elements:
          - cluster: k0s-cntrl
            url: https://10.1.1.40:443

          - cluster: infra1-dc1
            url: https://172.18.0.1:443

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{cluster}}-tls'
      
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true

      source:
        path: Security/TLS
        repoURL: https://github.com/EntraptaJ/Home1.resolvemy.host.git
        targetRevision: HEAD

      destination:
        server: '{{url}}'
        namespace: cert-manager