apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home1-resolvemyhost
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: '0'

spec:
  project: default

  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true

  source:
    repoURL: https://github.com/EntraptaJ/Home1.resolvemy.host.git
    targetRevision: HEAD
    path: nuc1.resolvemy.host
    directory:
      recurse: true

  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
