apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home1-network-backplane

  annotations:
    argocd.argoproj.io/sync-wave: '0'

spec:
  generators:
    - list:
        elements:
          - cluster: nuc1-home1
            url: https://kubernetes.default.svc

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{cluster}}-network-backplane'
      
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core

      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle

        - group: ''
          kind: ConfigMap
          name: hubble-ca-cert
          jsonPointers:
          - /data/ca.crt
        - group: ''
          kind: Secret
          name: hubble-relay-client-certs
          jsonPointers:
          - /data/ca.crt
          - /data/tls.crt
          - /data/tls.key
        - group: ''
          kind: Secret
          name: hubble-server-certs
          jsonPointers:
          - /data/ca.crt
          - /data/tls.crt
          - /data/tls.key


      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true

      source:
        path: Network/Backplane
        repoURL: https://github.com/EntraptaJ/Home1.resolvemy.host.git
        targetRevision: HEAD

      destination:
        server: '{{url}}'
        namespace: kube-system