apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home1-network-ingress

  annotations:
    argocd.argoproj.io/sync-wave: '1'

spec:
  generators:
    - list:
        elements:
          - cluster: nuc1-home1
            url: https://kubernetes.default.svc

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{cluster}}-network-ingress'
      
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core

      syncPolicy:
        automated: {}

        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true

      source:
        path: Network/Ingress
        repoURL: https://github.com/EntraptaJ/Home1.resolvemy.host.git
        targetRevision: HEAD

      destination:
        server: '{{url}}'
        namespace: kube-system