apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home1-network-ipam

  annotations:
    argocd.argoproj.io/sync-wave: '6'

spec:
  generators:
    - list:
        elements:
          - cluster: nuc1-home1
            url: https://kubernetes.default.svc

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{cluster}}-network-ipam'
      
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core

      syncPolicy:
        syncOptions:
          - ServerSideApply=true

      source:
        path: Network/IPAM
        repoURL: https://github.com/K-FOSS/CoRE-Backplane.git
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin


      destination:
        server: '{{url}}'
        namespace: core-prod