apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: esphome
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: '0'

spec:
  project: default

  syncPolicy:
    syncOptions:
      - ServerSideApply=true

  source:
    repoURL: https://github.com/EntraptaJ/Home1.resolvemy.host.git
    targetRevision: HEAD
    path: ESPHome
    plugin:
      name: argocd-lovely-plugin


  destination: 
    server: https://kubernetes.default.svc
    namespace: core-prod
