apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: home-main
  namespace: kube-system

  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: PodCIDR
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
          - ClusterIP
          - ExternalIP
      selector:             # <-- select all services
        matchExpressions:
         - {key: somekey, operator: NotIn, values: ['never-used-value']}

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: default
  namespace: kube-system
spec:
  transport:
    peerPort: 179
    localPort: 180
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: 'bgp'

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-cluster
  namespace: kube-system
spec:
  bgpInstances:
    - name: main
      localASN: 64567
      peers:
        - name: frr
          peerAddress: 127.0.0.1
          peerASN: 64567
          peerConfigRef:
            name: default