apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: main

  namespace: kube-system
spec:
  raw:
    priority: 5
    rawConfig: |
      router bgp 64567
        bgp allow-martian-nexthop
        neighbor cilium peer-group
        neighbor cilium remote-as internal
        bgp listen range 127.0.0.0/24 peer-group cilium
        bgp listen range 192.168.4.0/24 peer-group cilium
        address-family ipv4 unicast
          neighbor cilium activate
          neighbor cilium soft-reconfiguration inbound
  bgp:
    routers:
      - asn: 64567
        id: 172.31.241.253
        neighbors:
          - address: 172.31.241.249
            asn: 64567
            sourceaddress: 192.168.4.71
            port: 179
            toAdvertise:
              allowed:
                mode: all