apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: main

  namespace: kube-system
spec:
  bgp:
    routers:
      - asn: 64567
        id: 192.168.4.71
        neighbors:
          - address: 127.0.0.1
            asn: 64567
            port: 180
            sourceaddress: 127.0.0.1

          - address: 172.31.241.249
            asn: 64567
            sourceaddress: 172.31.241.253
            port: 179