apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: main

  namespace: kube-system
spec:
  bgp:
    routers:
      - asn: 64567
        id: 172.31.241.253
        prefixes:
          - 10.0.0.0/8
        neighbors:
          #
          # Cilium WIP
          # 
          - address: 192.168.4.71
            asn: 64567
            port: 5555
            toReceive:
              allowed:
                mode: all

          - address: 172.31.241.249
            asn: 64567
            sourceaddress: 192.168.4.71
            port: 179
            toAdvertise:
              allowed:
                mode: all