apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: main

  namespace: kube-system
spec:
  raw:
    priority: 5
    rawConfig: |-
      router bgp 64567
        neighbor cilium peer-group
        neighbor cilium remote-as internal
        bgp listen range 127.0.0.0/24 peer-group cilium
        bgp listen range 172.31.241.253/32 peer-group cilium
        bgp listen range 192.168.4.71/32 peer-group cilium

  bgp:
    routers:
      - asn: 64567
        id: 192.168.4.71
        prefixes:
          - 10.0.0.0/24
        neighbors:
          - address: 127.0.0.1
            asn: 64567
            toReceive:
              allowed:
                mode: all

          - address: 172.31.241.249
            asn: 64567
            sourceaddress: 172.31.241.253
            port: 179
            toAdvertise:
              allowed:
                mode: all